image: nixos/nix:latest

pages:
  before_script:
    - nix-env -iA nixpkgs.cachix nixpkgs.bash
    - cachix authtoken $CACHIX_AUTH_TOKEN
    - cachix use stites-io
    - nix path-info --all > /tmp/store-path-pre-build

  script:
    - nix-build ./release.nix
    - rm -rf public
    - mv _site public

  after_script:
    # push all store paths that were added during the build
    - bash -c "comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push stites-io"

  only:
    - master

  artifacts:
    paths:
      - public/*.html
      - public/*.pdf
      - public/*.ico
      - public/posts
      - public/images
      - public/drafts
      - public/css

cache:
  paths:
    - _cache
    - .cache
    - .stack
    # apparently this _must_ be cached.
    - public

# image: haskell:8.6                  # 300Mb
# image: fpco/stack-build:lts-14.11 # 3GB
# pages:
#   before_script:
#     - export STACK_ROOT="$(pwd)/.stack"
#     - stack install --only-dependencies
#     - stack build
#   script:
#     - sleep 2h
#     - stack exec site build
#       # - mv _site public
#   only:
#     - master
