image: haskell:8.6                  # 300Mb
# image: fpco/stack-build:lts-14.11 # 3GB

pages:
  cache:
    paths:
      - _cache
      - .stack
  before_script:
    - export STACK_ROOT="$(pwd)/.stack"
    - stack install --only-dependencies
    - stack build
  script:
    - sleep 1h
    - stack exec site build
      # - mv _site public
  artifacts:
    paths:
      - _site/*.html
      - _site/*.pdf
      - _site/*.ico
      - _site/posts
      - _site/images
      - _site/drafts
      - _site/css
  only:
    - master

