version: 2
jobs:
  build:
    parallelism: 4
    docker:
      # use any language to get access to circleci image
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "stites-io.cabal" }}
      - run:
          name: Install commercialhaskell/stack v1.6.3
          command: |
            curl -L https://github.com/commercialhaskell/stack/releases/download/v1.6.3/stack-1.6.3-linux-x86_64.tar.gz | tar zx -C /tmp
            sudo mv /tmp/stack-1.6.3-linux-x86_64/stack /usr/bin
      - run:
          name: Setup stack
          command: |
            sudo apt-get install libgmp3-dev
            stack setup
          no_output_timeout: 1200
      - run:
          name: build all dependencies with stack
          command: |
            stack build -j1 --fast --pedantic --haddock --test --no-run-tests --no-haddock-deps
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "stites-io.cabal" }}
          paths:
            - "~/.stack"
            - ".stack-work"

deployment:
  site:
    branch: master
    codedeploy:
      stites-io:
        application_root: /
        region: us-east-1
        revision_location:
          revision_type: S3
          s3_location:
            bucket: stites.io
            key_pattern: stites-io-{BRANCH}-{SHORT_COMMIT}
        deployment_group: stites-io_deploy

